{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "MongoDB Server",
                    "vendor": "MongoDB Inc.",
                    "versions": [
                        {
                            "lessThan": "3.6.11",
                            "status": "affected",
                            "version": "3.6",
                            "versionType": "custom"
                        },
                        {
                            "lessThan": "4.0.6",
                            "status": "affected",
                            "version": "4.0",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "datePublic": "2021-02-26T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A user authorized to performing a specific type of query may trigger a denial of service by issuing a generic explain command on a find query. This issue affects: MongoDB Inc. MongoDB Server v4.0 versions prior to 4.0.6; MongoDB Server v3.6 versions prior to 3.6.11."
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 4.9,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "exploitCodeMaturity": "FUNCTIONAL",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "HIGH",
                        "remediationLevel": "UNAVAILABLE",
                        "reportConfidence": "CONFIRMED",
                        "scope": "UNCHANGED",
                        "temporalScore": 4.8,
                        "temporalSeverity": "MEDIUM",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:N/A:H/E:F/RL:U/RC:C",
                        "version": "3.1"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-20",
                            "description": "CWE-20 Improper Input Validation",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-03-01T16:15:14",
                "orgId": "a39b4221-9bd0-4244-95fc-f3e2e07f1deb",
                "shortName": "mongodb"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://jira.mongodb.org/browse/SERVER-38275"
                }
            ],
            "source": {
                "discovery": "INTERNAL"
            },
            "title": "Invariant failure when explaining a find with a UUID",
            "x_generator": {
                "engine": "Vulnogram 0.0.9"
            },
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cna@mongodb.com",
                    "DATE_PUBLIC": "2021-02-26T17:00:00.000Z",
                    "ID": "CVE-2018-25004",
                    "STATE": "PUBLIC",
                    "TITLE": "Invariant failure when explaining a find with a UUID"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "MongoDB Server",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_affected": "<",
                                                        "version_name": "3.6",
                                                        "version_value": "3.6.11"
                                                    },
                                                    {
                                                        "version_affected": "<",
                                                        "version_name": "4.0",
                                                        "version_value": "4.0.6"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "MongoDB Inc."
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "A user authorized to performing a specific type of query may trigger a denial of service by issuing a generic explain command on a find query. This issue affects: MongoDB Inc. MongoDB Server v4.0 versions prior to 4.0.6; MongoDB Server v3.6 versions prior to 3.6.11."
                        }
                    ]
                },
                "generator": {
                    "engine": "Vulnogram 0.0.9"
                },
                "impact": {
                    "cvss": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 4.8,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "HIGH",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:N/A:H/E:F/RL:U/RC:C",
                        "version": "3.1"
                    }
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-20 Improper Input Validation"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://jira.mongodb.org/browse/SERVER-38275",
                            "refsource": "MISC",
                            "url": "https://jira.mongodb.org/browse/SERVER-38275"
                        }
                    ]
                },
                "source": {
                    "discovery": "INTERNAL"
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "a39b4221-9bd0-4244-95fc-f3e2e07f1deb",
        "assignerShortName": "mongodb",
        "cveId": "CVE-2018-25004",
        "datePublished": "2021-02-26T00:00:00",
        "dateReserved": "2021-01-29T00:00:00",
        "dateUpdated": "2021-03-01T16:15:14",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}