{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2018-11-18T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Jupyter Notebook before 5.7.1 allows XSS via an untrusted notebook because nbconvert responses are considered to have the same origin as the notebook server. In other words, nbconvert endpoints can execute JavaScript with access to the server API. In notebook/nbconvert/handlers.py, NbconvertFileHandler and NbconvertPostHandler do not set a Content Security Policy to prevent this."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2020-11-19T06:06:10",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://groups.google.com/forum/#%21topic/jupyter/hWzu2BSsplY"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://pypi.org/project/notebook/#history"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/jupyter/notebook/commit/107a89fce5f413fb5728c1c5d2c7788e1fb17491"
                },
                {
                    "name": "[debian-lts-announce] 20201119 [SECURITY] [DLA 2432-1] jupyter-notebook security update",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "https://lists.debian.org/debian-lts-announce/2020/11/msg00033.html"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2018-19351",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "Jupyter Notebook before 5.7.1 allows XSS via an untrusted notebook because nbconvert responses are considered to have the same origin as the notebook server. In other words, nbconvert endpoints can execute JavaScript with access to the server API. In notebook/nbconvert/handlers.py, NbconvertFileHandler and NbconvertPostHandler do not set a Content Security Policy to prevent this."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://groups.google.com/forum/#!topic/jupyter/hWzu2BSsplY",
                            "refsource": "MISC",
                            "url": "https://groups.google.com/forum/#!topic/jupyter/hWzu2BSsplY"
                        },
                        {
                            "name": "https://pypi.org/project/notebook/#history",
                            "refsource": "MISC",
                            "url": "https://pypi.org/project/notebook/#history"
                        },
                        {
                            "name": "https://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst",
                            "refsource": "MISC",
                            "url": "https://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst"
                        },
                        {
                            "name": "https://github.com/jupyter/notebook/commit/107a89fce5f413fb5728c1c5d2c7788e1fb17491",
                            "refsource": "MISC",
                            "url": "https://github.com/jupyter/notebook/commit/107a89fce5f413fb5728c1c5d2c7788e1fb17491"
                        },
                        {
                            "name": "[debian-lts-announce] 20201119 [SECURITY] [DLA 2432-1] jupyter-notebook security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2020/11/msg00033.html"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2018-19351",
        "datePublished": "2018-11-18T17:00:00",
        "dateReserved": "2018-11-18T00:00:00",
        "dateUpdated": "2020-11-19T06:06:10",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}