{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "pidgin",
                    "vendor": "Pidgin",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "2.12.0"
                        }
                    ]
                }
            ],
            "datePublic": "2018-07-27T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "An out-of-bounds write flaw was found in the way Pidgin before 2.12.0 processed XML content. A malicious remote server could potentially use this flaw to crash Pidgin or execute arbitrary code in the context of the pidgin process."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "HIGH",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 7.5,
                        "baseSeverity": "HIGH",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "HIGH",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "REQUIRED",
                        "vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-787",
                            "description": "CWE-787",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2018-07-28T09:57:01",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "GLSA-201706-10",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_GENTOO"
                    ],
                    "url": "https://security.gentoo.org/glsa/201706-10"
                },
                {
                    "name": "RHSA-2017:1854",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2017:1854"
                },
                {
                    "name": "96775",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_BID"
                    ],
                    "url": "http://www.securityfocus.com/bid/96775"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2640"
                },
                {
                    "name": "DSA-3806",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_DEBIAN"
                    ],
                    "url": "https://www.debian.org/security/2017/dsa-3806"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2017-2640",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "pidgin",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "2.12.0"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "Pidgin"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "An out-of-bounds write flaw was found in the way Pidgin before 2.12.0 processed XML content. A malicious remote server could potentially use this flaw to crash Pidgin or execute arbitrary code in the context of the pidgin process."
                        }
                    ]
                },
                "impact": {
                    "cvss": [
                        [
                            {
                                "vectorString": "7.5/CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                                "version": "3.0"
                            }
                        ]
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-787"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "GLSA-201706-10",
                            "refsource": "GENTOO",
                            "url": "https://security.gentoo.org/glsa/201706-10"
                        },
                        {
                            "name": "RHSA-2017:1854",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2017:1854"
                        },
                        {
                            "name": "96775",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/96775"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2640",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2640"
                        },
                        {
                            "name": "DSA-3806",
                            "refsource": "DEBIAN",
                            "url": "https://www.debian.org/security/2017/dsa-3806"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2017-2640",
        "datePublished": "2018-07-27T18:00:00",
        "dateReserved": "2016-12-01T00:00:00",
        "dateUpdated": "2018-07-28T09:57:01",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}