{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "pimcore/pimcore",
                    "vendor": "pimcore",
                    "versions": [
                        {
                            "lessThan": "10.2.7",
                            "status": "affected",
                            "version": "unspecified",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Unrestricted Upload of File with Dangerous Type in Packagist pimcore/pimcore prior to 10.2.7."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "LOCAL",
                        "availabilityImpact": "HIGH",
                        "baseScore": 6.6,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "LOW",
                        "integrityImpact": "LOW",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:H",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-434",
                            "description": "CWE-434 Unrestricted Upload of File with Dangerous Type",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-18T15:55:10",
                "orgId": "c09c270a-b464-47c1-9133-acb35b22c19a",
                "shortName": "@huntrdev"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://huntr.dev/bounties/96506857-06bc-4c84-88b7-4f397715bcf6"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/pimcore/pimcore/commit/35d1853baf64d6a1d90fd8803e52439da53a3911"
                }
            ],
            "source": {
                "advisory": "96506857-06bc-4c84-88b7-4f397715bcf6",
                "discovery": "EXTERNAL"
            },
            "title": "Unrestricted Upload of File with Dangerous Type in pimcore/pimcore",
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "security@huntr.dev",
                    "ID": "CVE-2022-0263",
                    "STATE": "PUBLIC",
                    "TITLE": "Unrestricted Upload of File with Dangerous Type in pimcore/pimcore"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "pimcore/pimcore",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_affected": "<",
                                                        "version_value": "10.2.7"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "pimcore"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "Unrestricted Upload of File with Dangerous Type in Packagist pimcore/pimcore prior to 10.2.7."
                        }
                    ]
                },
                "impact": {
                    "cvss": {
                        "attackComplexity": "LOW",
                        "attackVector": "LOCAL",
                        "availabilityImpact": "HIGH",
                        "baseScore": 6.6,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "LOW",
                        "integrityImpact": "LOW",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:H",
                        "version": "3.0"
                    }
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-434 Unrestricted Upload of File with Dangerous Type"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://huntr.dev/bounties/96506857-06bc-4c84-88b7-4f397715bcf6",
                            "refsource": "CONFIRM",
                            "url": "https://huntr.dev/bounties/96506857-06bc-4c84-88b7-4f397715bcf6"
                        },
                        {
                            "name": "https://github.com/pimcore/pimcore/commit/35d1853baf64d6a1d90fd8803e52439da53a3911",
                            "refsource": "MISC",
                            "url": "https://github.com/pimcore/pimcore/commit/35d1853baf64d6a1d90fd8803e52439da53a3911"
                        }
                    ]
                },
                "source": {
                    "advisory": "96506857-06bc-4c84-88b7-4f397715bcf6",
                    "discovery": "EXTERNAL"
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "c09c270a-b464-47c1-9133-acb35b22c19a",
        "assignerShortName": "@huntrdev",
        "cveId": "CVE-2022-0263",
        "datePublished": "2022-01-18T15:55:10",
        "dateReserved": "2022-01-17T00:00:00",
        "dateUpdated": "2022-01-18T15:55:10",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}