{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "kernel",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "Not Known"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A flaw was found in the Linux kernel. Measuring usage of the shared memory does not scale with large shared memory segment counts which could lead to resource exhaustion and DoS."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-400",
                            "description": "CWE-400 - Uncontrolled Resource Consumption",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-08-26T15:25:40",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1986473"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1980619"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://access.redhat.com/security/cve/CVE-2021-3669"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://security-tracker.debian.org/tracker/CVE-2021-3669"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2021-3669",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "kernel",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "Not Known"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "A flaw was found in the Linux kernel. Measuring usage of the shared memory does not scale with large shared memory segment counts which could lead to resource exhaustion and DoS."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-400 - Uncontrolled Resource Consumption"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1986473",
                            "refsource": "MISC",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1986473"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1980619",
                            "refsource": "MISC",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1980619"
                        },
                        {
                            "name": "https://access.redhat.com/security/cve/CVE-2021-3669",
                            "refsource": "MISC",
                            "url": "https://access.redhat.com/security/cve/CVE-2021-3669"
                        },
                        {
                            "name": "https://security-tracker.debian.org/tracker/CVE-2021-3669",
                            "refsource": "MISC",
                            "url": "https://security-tracker.debian.org/tracker/CVE-2021-3669"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2021-3669",
        "datePublished": "2022-08-26T15:25:40",
        "dateReserved": "2021-07-29T00:00:00",
        "dateUpdated": "2022-08-26T15:25:40",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}